name: tweakwcs
channels:
    - defaults
dependencies:
    - "python>=3.5"
    - setuptools
    - numpy
    - numpydoc
    - "astropy>=3.1"
    - graphviz
    - pip:
      - "sphinx<=1.8.5"
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
      - matplotlib
      - gwcs
      - stsci.imagestats
      - stsci.stimage
      - spherical_geometry
      - git+https://github.com/spacetelescope/jwst#egg=jwst
